const lyrics = [
    {
        "album": "The Rise and Fall of a Midwest Princess",
        "songs": [
            {
                "song": "Femininomenon",
                "lyrics": [
                    "Same old story, time again",
                    "Got so close but then you lost it",
                    "Should've listened to your friends",
                    "About his girlfriend back in Boston",
                    "You sent him pictures and playlists and phone sex",
                    "He disappeared from the second that you said",
                    "Let's get coffee, let's meet up",
                    "I'm so sick of online love",
                    "And I don't understand",
                    "Why can't any man",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a fem...",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a-",
                    "(Uhm, can you play a song with a fucking beat?)",
                    "Hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "(Hit it like), hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "So let's say it's working out",
                    "You pretend to love his mother",
                    "Lying to your friends about how he's such a goddamn good lover",
                    "Stuck in the suburbs, you're folding his laundry",
                    "Got what you wanted so stop feeling sorry",
                    "Crying at the nail salon", 
                    "I'm so sick of online love",
                    "And I don't understand",
                    "Why can't any man",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a fem...",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a-",
                    "(Dude, can you play a song with a fucking beat?)",
                    ", hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "(Hit it like), hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "Ladies",
                    "You know what I mean",
                    "And you know what you need",
                    "And so does he",
                    "But does it happen?",
                    "(A what?)",
                    ", hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "(Hit it like), hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "Hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "(Hit it like), hit it like rom-pom-pom-pom",
                    "(Get it hot), get it hot like Papa John",
                    "(Make a bitch), make a bitch go on and on",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a fem...",
                    "Hit it like...",
                    "Get it hot...",
                    "Make a bitch...",
                    "It's a fem (fem, fem, fem)",
                ]
            },
            {
                "song": "Red Wine Supernova",
                "lyrics": [
                    "She was a playboy, Brigitte Bardot",
                    "She showed me things, I didn't know",
                    "She did it right there, out on the deck",
                    "Put her canine teeth in the side of my neck",
                    "I'm in the hallway waiting for you",
                    "Miniskirt and my go-go boots (uh-huh)",
                    "I just want you to make a move",
                    "So slow down, sit down, it's new",
                    "I just wanna get to know you",
                    "Guess I didn't quite think it through (nah-uh, girl)",
                    "Fell in love with the thought of you",
                    "Now I'm choked up, face down, burnt out",
                    "Baby, why don't you come over?",
                    "Falling into me",
                    "(Let's pick it up now)",
                    "I don't care that you're a stoner",
                    "Fall right into me",
                    "I like (I like) what you like (what you like)",
                    "Long hair (no bra), that's my type (that's right)",
                    "You just told me, want me to fuck you",
                    "Baby, I will 'cause I really want to",
                    "I just wanna get to know you",
                    "Guess I didn't quite think it through (nah-uh, girl)",
                    "Fell in love with the thought of you",
                    "Now I'm choked up, face down, burnt out",
                    "Baby, why don't you come over?",
                    "Falling into me",
                    "(Okay, y'all, let's pick it up now)",
                    "I don't care that you're a stoner",
                    "Fall right into me",
                    "Well, back at my house, I got a California king",
                    "Okay, maybe it's a twin bed",
                    "And some roommates, don't worry, we're cool",
                    "I heard you like magic, I've got a wand and a rabbit",
                    "So baby, let's get freaky, get kinky",
                    "Let's make this bed get squeaky",
                    "Baby, why don't you come over?",
                    "Falling into me",
                    "I don't care that you're a stoner",
                    "Fall right into me",
                ]
            },
            {
                "song": "After Midnight",
                "lyrics": [
                    "My mama said nothing good happens",
                    "When it's late and you're dancing alone",
                    "She's in my head saying it's not attractive",
                    "Wearing that dress and red lipstick",
                    "This is what I wanted, this is what I like",
                    "I've been a good, good girl for a long time",
                    "But baby, I like flirting, a lover by my side",
                    "Can't be a good, good girl even if I tried",
                    "'Cause after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the club lights",
                    "I kinda wanna kiss your girlfriend",
                    "If you don't mind",
                    "I love a little drama, let's start a bar fight",
                    "'Cause everything good happens after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the club lights",
                    "I kinda wanna kiss your boyfriend",
                    "If you don't mind",
                    "I love a little uh-huh, let's watch the sunrise",
                    "Cause everything good happens after",
                    "I really want your hands on my body",
                    "A slow dance, baby, let's get it on",
                    "That's my type of fun, that's my kind of party",
                    "Your hands on my body, your hot hands",
                    "This is what I wanted, this is what I like",
                    "I've been a good, good girl for a long time",
                    "But baby, I like flirting, a lover by my side",
                    "Can't be a good, good girl even if I tried",
                    "'Cause after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the club lights",
                    "I kinda wanna kiss your girlfriend",
                    "If you don't mind",
                    "I love a little drama, let's start a bar fight",
                    "'Cause everything good happens after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the club lights",
                    "I kinda wanna kiss your boyfriend",
                    "If you don't mind",
                    "I love a little uh-huh, let's watch the sunrise",
                    "'Cause everything good happens after midnight",
                    "Baby, put your hands up",
                    "Be a freak in the club",
                    "Yeah, we'll make a move then we're making out",
                    "Yeah, we'll make, make love",
                    "Yeah, we'll make, make love",
                    "Be a freak in the club",
                    "Be a freak in the club",
                    "It's after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the club lights",
                    "I kinda wanna kiss your girlfriend",
                    "If you don't mind (if you don't, if you don't mind)",
                    "I love a little drama, let's start a bar fight",
                    "(Everybody wants make a little love, get drunk)",
                    "'Cause everything good happens after midnight",
                    "I'm feeling kinda freaky",
                    "Maybe it's the moonlight",
                    "I kinda wanna kiss your boyfriend",
                    "If you don't mind (if you don't, if you don't mind)",
                    "I love a little uh-huh, let's watch the sunrise",
                    "'Cause everything good happens after",
                ]
            },
            {
                "song": "Coffee",
                "lyrics": [
                    "Can't meet you for dinner at the Italian place",
                    "It's where I met your family, some words were exchanged",
                    "I'd suggest the jazz bar on Maryann Street, but",
                    "You'd buy me a drink, and we know where that leads, so",
                    "I'll meet you for coffee 'cause if we have wine",
                    "You'll say that you want me, I know that's a lie",
                    "If I didn't love you, it would be fine",
                    "I'll meet you for coffee, only for coffee",
                    "Nowhere else is safe, every place leads back to your place",
                    "You said, 'Let's do the park, 'cause I love the park",
                    "And that may be true, but God forbid it gets dark",
                    "Here come the excuses that fuel the illusions",
                    "But I'd rather feel something than nothing at all, so",
                    "I'll meet you for coffee 'cause if we have wine",
                    "You'll say that you're sorry, I know that's a lie",
                    "If I didn't trust you, it would be fine",
                    "I'll meet you for coffee, only for coffee",
                    "Nowhere else is safe, every place leads back to your-",
                    "We've done this before",
                    "And I don't need it anymore",
                    "So let's not do coffee, let's not even try",
                    "It's better we leave it and give it some time",
                    "If I didn't love you, it would be fine",
                    "'Cause If we do coffee, it's never just coffee",
                    "And it's never just coffee",
                ]
            },
            {
                "song": "Casual",
                "lyrics": [
                    "My friends call me a loser",
                    "Cause I'm still hanging around",
                    "I've heard so many rumors",
                    "That I'm just a girl that you bang on your couch",
                    "I thought you thought of me better",
                    "Someone you couldn't lose",
                    "You said, 'We're not together'",
                    "So now when we kiss, I have anger issues",
                    "You said, 'Baby, no attachment'",
                    "Knee deep in the passenger seat, and you're eating me out",
                    "Is it casual now?",
                    "Two weeks, and your mom invites me to her house on Long Beach",
                    "Is it casual now?",
                    "I know what you tell your friends",
                    "It's casual, if it's casual now",
                    "Then, baby, get me off again",
                    "If it's casual, it's casual now",
                    "Dumb love, I love being stupid",
                    "Dream of us in a year",
                    "Maybe we'd have an apartment",
                    "And you'd show me off to your friends at the pier",
                    "I know, 'Baby, no attachment'",
                    "Knee deep in the passenger seat, and you're eating me out",
                    "Is it casual now?",
                    "Two weeks, and your mom invites me to her house on Long Beach",
                    "Is it casual now?",
                    "I know what you tell your friends",
                    "It's casual, if it's casual now",
                    "Then, baby, get me off again",
                    "If it's casual",
                    "It's hard being casual",
                    "When my favorite bra lives in your dresser",
                    "And it's hard being casual",
                    "When I'm on the phone talking down your sister",
                    "And I try to be the chill girl",
                    "That holds her tongue and gives you space",
                    "I try to be the chill girl",
                    "But honestly, I'm not",
                    "Knee deep in the passenger seat, and you're eating me out",
                    "Two weeks, and your mom invites me to her Long Beach house",
                    "I know what you tell your friends",
                    "Baby, get me off again",
                    "I fucked you in the bathroom when we went to dinner",
                    "Your parents at the table, you wonder why I'm bitter",
                    "Bragging to your friends, I get off when you hit it",
                    "I hate to tell the truth, but I'm sorry, dude, you didn't",
                    "I hate that I let this drag on so long, now I hate myself",
                    "Hate that I let this drag on so long, you can go to hell",
                ]
            },
            {
                "song": "Super Graphic Ultra Modern Girl",
                "lyrics": [
                    "You know what they say",
                    "Never waste a Friday night on a first date",
                    "In my heels with my hair straight",
                    "And so, I take him to this bar",
                    "This man wouldn't dance",
                    "He didn't ask a single question",
                    "And he was wearing these fugly jeans",
                    "It doesn't matter though, he doesn't have what it takes",
                    "To be with a girl like me",
                    "Not overdramatic, I know what I want",
                    "We're leaving the planet and you can't come",
                    "Uh huh, I'm through",
                    "With all these super mega bummer boys like you",
                    "A super graphic ultra-modern girl like me",
                    "We're high, we're drunk",
                    "Well, look at her moving baby, she's the one",
                    "Oh yeah, I need",
                    "A super graphic ultra-modern girl like me",
                    "Telling secrets, there on the mattress",
                    "Wearing nothing but glitter and lashes",
                    "At every party, we're the party, shaking our asses",
                    "Making out (uh huh) while the world collapses",
                    "Not overdramatic, I know what I want",
                    "We're leaving the planet and you can't come",
                    "Uh huh, I'm through",
                    "With all these super mega bummer boys like you",
                    "Oh yeah, I need",
                    "A super graphic ultra-modern girl like me",
                    "We're high, we're drunk",
                    "Well, look at her moving baby, she's the one",
                    "A super graphic ultra-modern girl like me",
                    "Get up off your feet, get up on that bar",
                    "Walk that walk from Tokyo to New York",
                    "With everything you feel and everything you are",
                    "Walk that walk, flash the camera",
                    "Flash the camera, flash the camera, you're a star",
                    "Uh huh (uh huh), I'm through (I'm through)",
                    "With all these stupid mega bummer boys like you",
                    "Oh yeah (oh yeah), I need (I need)",
                    "A super graphic ultra-modern girl like me",
                    "We're high, we're drunk",
                    "Well, look at her moving baby, she's the one",
                    "Oh yeah (oh yeah), I need (I need)",
                    "A super graphic ultra-modern, oh, you got me la-la-la-ling",
                ]
            },
            {
                "song": "HOT TO GO!",
                "lyrics": [
                    "Five, six",
                    "Five, six, seven, eight",
                    "I could be the one, or your new addiction",
                    "It's all in my head but I want non-fiction",
                    "I don't want the world, but I'll take this city",
                    "Who can blame a girl? Call me hot, not pretty",
                    "Baby, do you like this beat? (Na-na-na-na, na)",
                    "I made it so you'd dance with me (na-na-na-na, na)",
                    "It's like a hundred ninety-nine degrees (na-na-na-na, na)",
                    "When you're doing it with me, doing it with me (na-na-na-na, na)", 
                    "Snap and clap and touch your toes",
                    "Raise your hands, now body roll",
                    "Dance it out, you're hot to go",
                    "Snap and clap and touch your toes",
                    "Raise your hands, now body roll",
                    "You can take me hot to go",
                    "Well, I woke up alone staring at my ceiling",
                    "I try not to care but it hurts my feelings",
                    "You don't have to stare, come here, get with it",
                    "No one's touched me there in a damn hot minute",
                    "And baby, don't you like this beat? (Na-na-na-na, na)",
                    "I made it so you'd sleep with me (na-na-na-na, na)",
                    "It's like a hundred ninety-nine degrees (na-na-na-na, na)",
                    "When you're doing it with me, doing it with me (na-na-na-na, na)",
                    "Snap and clap and touch your toes",
                    "Raise your hands, now body roll",
                    "Dance it out, you're hot to go",
                    "Snap and clap and touch your toes",
                    "Raise your hands, now body roll",
                    "You can take me hot to go",
                    "You can take me hot to go",
                    "What's it take to get your number?",
                    "What's it take to bring you home?",
                    "Hurry up, it's time for supper",
                    "Order up, I'm hot to go",
                    "What's it take to get your number?",
                    "Hurry up, it's getting cold",
                    "Hurry up, it's time for supper",
                    "Order up, I'm hot to go",
                    "You can take me hot to go (oh, yeah)",
                    "You can take me hot to go (hot to go)",
                    "You can take me hot to go (oh, yeah)",
                    "You can take me hot to go",
                    "Whew, it's hot here",
                    "Is anyone else hot?",
                    "Woo, you coming home with me?",
                    "Okay, it's hot",
                    "I'll call the cab",
                ]
            },
            {
                "song": "Picture You",
                "lyrics": [
                    "Draw the blinds",
                    "Light every candle",
                    "Slip off my pretty dress down my chest",
                    "While I think of you",
                    "Every night",
                    "Both lips on the mirror",
                    "It's ritualistic, counting lipstick",
                    "Stains where you should be",
                    "Am I in the frame from your point of view? (Oh)",
                    "Do you feel the same? I'm too scared to say (oh)",
                    "Half of the things I do",
                    "So, tell me now (tell me now)",
                    "All your perversions (oh, oh)",
                    "Am I doing research (am I?) in a mini skirt",
                    "At the library in your hometown?",
                    "I need you around",
                    "I'm getting close now",
                    "Am I in the frame from your point of view? (Oh)",
                    "Do you feel the same? I'm too scared to say (oh)",
                    "Half of the things I do",
                ]
            },
            {
                "song": "Kaleidoscope",
                "lyrics": [
                    "Here we go again",
                    "Everything is fine",
                    "I guess we could pretend",
                    "We didn't cross a line",
                    "But ever since that day",
                    "Everything has changed",
                    "The way I write your name",
                    "The cursive letter A",
                    "Whenever it may be",
                    "That you go on your way",
                    "If you really wanna leave",
                    "I'll never make you stay",
                    "Whatever you decide",
                    "I will understand",
                    "And it will all be fine",
                    "Just go back to being friends",
                    "And love is a kaleidoscope",
                    "How it works we'll never know",
                    "And even all the change",
                    "Is somehow all the same",
                    "Turnin' to the left and right",
                    "Colors shining in your eye",
                    "And even upside down",
                    "It's beautiful somehow",
                    "It's never just a shape alone",
                    "Love is a kaleidoscope",
                    "And if you ever find",
                    "Someone who could write",
                    "A better song for you",
                    "Well I'd love to see them try",
                    "Put it all in words",
                    "And sing it all in tune",
                    "There's no one else who could",
                    "The only one is you",
                    "And if you change your mind",
                    "I will understand",
                    "And it'll just take time",
                    "To go back to being friends",
                    "And love is a kaleidoscope",
                    "How it works we'll never know",
                    "And even all the change",
                    "Is somehow all the same",
                    "Turning to the left and right",
                    "Colors shining in your eye",
                    "And even upside down",
                    "It's beautiful somehow",
                    "Every color of the rainbow",
                    "Don't be afraid to hold it close",
                    "It's never just a shape alone",
                ]
            },
            {
                "song": "Pink Pony Club",
                "lyrics": [
                    "I know you wanted me to stay",
                    "But I can't ignore the crazy visions of me in LA",
                    "And I heard that there's a special place",
                    "Where boys and girls can all be queens every single day",
                    "I'm having wicked dreams",
                    "Of leaving Tennessee",
                    "Oh, Santa Monica",
                    "I swear it's calling me",
                    "Won't make my mama proud",
                    "It's gonna cause a scene",
                    "She sees her baby girl",
                    "I know she's gonna scream",
                    "God, what have you done",
                    "You're a pink pony girl",
                    "And you dance at the club",
                    "Oh mama, I'm just having fun",
                    "On the stage in my heels",
                    "It's where I belong down at the",
                    "I'm gonna keep on dancing at the",
                    "I'm gonna keep on dancing down in",
                    "West Hollywood",
                    "I'm up and jaws are on the floor",
                    "Lovers in the bathroom and a line outside the door",
                    "Blacklights and a mirrored disco ball",
                    "Every night's another reason why I left it all",
                    "I thank my wicked dreams",
                    "A year from Tennessee",
                    "Oh, Santa Monica",
                    "You've been too good to be",
                    "Won't make my mama proud",
                    "It's gonna cause a scene",
                    "She sees her baby girl",
                    "I know she's gonna scream",
                    "God, what have you done",
                    "You're a pink pony girl",
                    "And you dance at the club",
                    "Oh mama, I'm just having fun",
                    "On the stage in my heels",
                    "It's where I belong down at the",
                    "I'm gonna keep on dancing at the",
                    "I'm gonna keep on dancing down in",
                    "West Hollywood",
                    "Don't think I've left you all behind",
                    "Still love you and Tennessee",
                    "You're always on my mind",
                    "And mama, every Saturday",
                    "I can hear your southern draw a thousand miles away, saying",
                    "God, what have you done",
                    "You're a pink pony girl",
                    "And you dance at the club",
                    "Oh mama, I'm just having fun",
                    "On the stage in my heels",
                    "It's where I belong down at the",
                    "I'm gonna keep on dancing at the",
                    "I'm gonna keep on dancing down in",
                    "West Hollywood",
                    "I'm gonna keep on dancing at the",
                    "I'm gonna keep on dancing",
                    "I'm gonna keep on dancing",
                ]
            },
            {
                "song": "Guilty Pleasure",
                "lyrics": [
                    "Learned it on the internet",
                    "Wheels turning in my head",
                    "Think back to what you said",
                    "And I turn red, I'm turning red",
                    "Wild thoughts that make me melt",
                    "A good hit below the belt",
                    "Sometimes I scare myself",
                    "But I can't help what I can't help",
                    "So shame on me and shame on you",
                    "I fantasize what we would do",
                    "And how would it taste and the way you move",
                    "Oh, some good girls do bad things too",
                    "I want this like a cigarette",
                    "Can we drag it out and never quit?",
                    "And oh my god, you are heaven sent",
                    "With your dirty mind, yeah, you're perverted",
                    "It's been awhile since you turned up the dial",
                    "So shame on me (shame on me), shame on you (shame on you)",
                    "I fantasize what we would do (we would do)",
                    "And how would it taste, the way you move",
                    "Oh, some good girls do bad things too",
                    "I want this like a cigarette",
                    "Can we drag it out and never quit?",
                    "And oh my god, you are heaven sent",
                    "With your dirty mind, yeah, you're perverted"
                ]
            },
            {
                "song": "Naked in Manhattan",
                "lyrics": [
                    "New crush, high school love again",
                    "The rush of slumber party kissing",
                    "Don't touch, I'll never cross the line",
                    "So I pushed you down a million times",
                    "I'd love if you knew you were on my mind",
                    "Constant like cicadas in the summertime",
                    "Boys suck and girls I've never tried",
                    "And we both know we're getting drunk tonight",
                    "Touch me, baby, put your lips on mine",
                    "Could go to hell but we'll probably be fine",
                    "I know you want it, baby, you can have it",
                    "Oh, I've never done it, let's make it cinematic",  
                    "Like that one sex scene that's in Mulholland Drive",
                    "I wanna know, baby, what is it like?",
                    "I know you want it, baby, you can have it",
                    "A Pisces, who knew that we were so aligned",
                    "When I sing that Lana song, it makes you cry",
                    "Mean Girls, we watch it every night",
                    "And we both have a crush on Regina George",
                    "You love peach and ice cream",
                    "Bedazzled, Chanel rings",
                    "In New York, you can try things",
                    "An inch away from more than just friends",
                    "Touch me, baby, put your lips on mine",
                    "Could go to hell but we'll probably be fine",
                    "I know you want it, baby, you can have it",
                    "Hair clips and lip gloss",
                    "French kiss sittin' crisscrossed",
                    "But don't try and it's my loss",
                    "An inch away from more than just friends",
                ]
            },
        ]
    },
    {
        "album": "Good Luck, Babe!",
        "songs": [
            {
                "song": "Good Luck, Babe!",
                "lyrics": [
                    "It's fine, it's cool",
                    "You can say that we are nothing, but you know the truth",
                    "And guess I'm the fool",
                    "With her arms out like an angel through the car sunroof",
                    "I don't wanna call it off",
                    "But you don't wanna call it love",
                    "You only wanna be the one that I call 'baby'",
                    "You can kiss a hundred boys in bars",
                    "Shoot another shot, try to stop the feeling",
                    "You can say it's just the way you are",
                    "Make a new excuse, another stupid reason",
                    "You'd have to stop the world just to stop the feeling",
                    "You'd have to stop the world just to stop the feeling",
                    "I'm cliché, who cares?",
                    "It's a sexually explicit kind of love affair",
                    "And I cry, it's not fair",
                    "I just need a little lovin', I just need a little air",
                    "Think I'm gonna call it off",
                    "Even if you call it love",
                    "I just wanna love someone who calls me 'baby'",
                    "You can kiss a hundred boys in bars",
                    "Shoot another shot, try to stop the feeling",
                    "You can say it's just the way you are",
                    "Make a new excuse, another stupid reason",
                    "You'd have to stop the world just to stop the feeling",
                    "You'd have to stop the world just to stop the feeling",
                    "When you wake up next to him in the middle of the night",
                    "With your head in your hands, you're nothing more than his wife",
                    "And when you think about me, all of those years ago",
                    "You're standing face to face with 'I told you so'",
                    "You know I hate to say, 'I told you so'",
                    "You know I hate to say, but, I told you so",
                    "You can kiss a hundred boys in bars",
                    "Shoot another shot, try to stop the feeling (well, I told you so)",
                    "You can say it's just the way you are",
                    "Make a new excuse, another stupid reason",
                    "You'd have to stop the world just to stop the feeling",
                    "You'd have to stop the world just to stop the feeling",
                    "You'd have to stop the world just to stop the feeling",
                ]
            }
        ]
    }
]

export default lyrics;